services:
  telegram_rss:
    build: .
    container_name: telegram_rss
    restart: unless-stopped
    environment:
      - API_ID=XXXXXXXX
      - API_HASH=xXXXxXXxXxxxxxxxXXxXXxxxXXXXXXXXxxx
      - CHANNELS=cKure,zer0day1ab,thebugbountyhunter # Add more channels
    ports:
      - "3002:3002"
    volumes:
      - ./session_name.session:/app/session_name.session
